### ISSUE TITLE
requirements.txt requires matplotlib 2.1.2 but that doesn't work with python 3.8

### ISSUE THREAD

**Issue by llorracc** [econ-ark/REMARK#75]
I looked again at the transcript of my code that creates my VM and it was in the installation of the REMARKs rather than DemARKs that the error occurred.

```
+ pip install -r requirements.txt
Collecting matplotlib==2.1.2
  Downloading matplotlib-2.1.2.tar.gz (36.2 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c6nqlpuv/matplotlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c6nqlpuv/matplotlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-c6nqlpuv/matplotlib/pip-egg-info
         cwd: /tmp/pip-install-c6nqlpuv/matplotlib/
    Complete output (71 lines):
    ============================================================================
    Edit setup.cfg to change the build options
    
    BUILDING MATPLOTLIB
                matplotlib: yes [2.1.2]
                    python: yes [3.8.2 (default, Jul 16 2020, 14:00:26)  [GCC
                            9.3.0]]
                  platform: yes [linux]
    
    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [version 1.19.1]
                       six: yes [using six version 1.14.0]
                  dateutil: yes [using dateutil version 2.7.3]
    backports.functools_lru_cache: yes [Not required]
              subprocess32: yes [Not required]
                      pytz: yes [using pytz version 2020.1]
                    cycler: yes [using cycler version 0.10.0]
                   tornado: yes [using tornado version 6.0.4]
                 pyparsing: yes [using pyparsing version 2.4.7]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: no  [The C/C++ header for freetype2 (ft2build.h)
                            could not be found.  You may need to install the
                            development package.]
                       png: no  [pkg-config information for 'libpng' could not
                            be found.]
                     qhull: yes [pkg-config information for 'libqhull' could not
                            be found. Using local copy.]
    
    OPTIONAL SUBPACKAGES
               sample_data: yes [installing]
                  toolkits: yes [installing]
                     tests: no  [skipping due to configuration]
            toolkits_tests: no  [skipping due to configuration]
    
    OPTIONAL BACKEND EXTENSIONS
                    macosx: no  [Mac OS-X only]
                    qt5agg: no  [PySide2 not found; PyQt5 not found]
                    qt4agg: no  [PySide not found; PyQt4 not found]
    Unable to init server: Could not connect: Connection refused
    Unable to init server: Could not connect: Connection refused
                   gtk3agg: yes [installing, version 3.20.24]
    Unable to init server: Could not connect: Connection refused
    Unable to init server: Could not connect: Connection refused
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-c6nqlpuv/matplotlib/setup.py", line 216, in <module>
        pkg_help = pkg.install_help_msg()
      File "/tmp/pip-install-c6nqlpuv/matplotlib/setupext.py", line 595, in install_help_msg
        release = platform.linux_distribution()[0].lower()
    AttributeError: module 'platform' has no attribute 'linux_distribution'
                 gtk3cairo: yes [installing, version 3.20.24]
                    gtkagg: no  [Requires pygtk]
                     tkagg: yes [installing; run-time loading from Python Tcl /
                            Tk]
                     wxagg: no  [requires wxPython]
                       gtk: no  [Requires pygtk]
                       agg: yes [installing]
                     cairo: yes [installing, pycairo version 1.16.2]
                 windowing: no  [Microsoft Windows only]
    
    OPTIONAL LATEX DEPENDENCIES
                    dvipng: no
               ghostscript: yes [version 9.50]
                     latex: no
                   pdftops: yes [version 0.86.1]
    
    OPTIONAL PACKAGE DATA
                      dlls: no  [skipping due to configuration]
    
    ============================================================================
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by MridulS** [comment]
I have updated the requirements.txt, but very soon it will be redundant as individual REMARKs will live in their own repositories with their own specific requirements. :)

**Comment by llorracc** [comment]
This problem should go away when we restructure the REMARKs
